[workspace]
default-members = ["crates/*"]
members = [
  "cli",
  "crates/*",
  "webui",
]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
