[package]
edition = "2021"
name = "rockbox-cli"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0.90"
clap = "4.5.17"
owo-colors = "4.1.0"
rockbox-library = {path = "../library"}
tokio = {version = "1.36.0", features = ["full"]}
