[package]
edition = "2021"
name = "rockbox-library"
version = "0.1.0"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
cuid = "1.3.3"
futures = "0.3.30"
md5 = "0.7.0"
owo-colors = "4.1.0"
rockbox-sys = {path = "../sys"}
sqlx = {version = "0.8.2", features = ["runtime-tokio", "tls-rustls", "sqlite", "chrono", "derive", "macros"]}
tokio = {version = "1.36.0", features = ["full"]}
