[package]
edition = "2021"
name = "rockbox-sys"
version = "0.1.0"

[dependencies]
anyhow = "1.0.89"
reqwest = {version = "0.12.7", features = ["rustls-tls", "json", "blocking"], default-features = false}
rockbox-traits = {path = "../traits"}
serde = {version = "1.0.210", features = ["derive"]}
url = "2.3.1"
