[package]
edition = "2021"
name = "rockbox-server"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
owo-colors = "4.0.0"
reqwest = {version = "0.12.7", features = ["blocking", "rustls-tls"], default-features = false}
rockbox-graphql = {path = "../graphql"}
rockbox-rpc = {path = "../rpc"}
rockbox-sys = {path = "../sys"}
serde_json = "1.0.128"
tokio = {version = "1.40.0", features = ["full"]}
