[package]
edition = "2021"
name = "rockbox-server"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
owo-colors = "4.0.0"
rockbox-graphql = {path = "../graphql"}
rockbox-rpc = {path = "../rpc"}
rockbox-sys = {path = "../sys"}
tokio = {version = "1.40.0", features = ["full"]}
