name: ci
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish image
        uses: fluentci-io/setup-fluentci@v5
        with:
          dagger-version: 0.13.0
          plugin: .
          args: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: tsirysndr
