name: release desktop
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish"
        type: "string"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Fluent CI and build webui
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          pipeline: bun
          args: |
            run build:electron
          working-directory: webui/rockbox
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List files
        run: ls -ltr release/*
        working-directory: webui/rockbox
      - name: Prepare release assets
        run: |
          shasum -a 256 rockbox_${{ env.RELEASE_VERSION }}.AppImage > rockbox_${{ env.RELEASE_VERSION }}.AppImage.sha256
        working-directory: webui/rockbox/release/${{ env.RELEASE_VERSION }}
        env:
          RELEASE_VERSION: v${{ inputs.tag || github.ref_name }}
      - name: Upload release assets
        run: |
          for ext in tar.gz AppImage tar.gz.sha256 AppImage.sha256; do
            export FILE=rockbox_${{ env.RELEASE_VERSION }}.$ext
            fluentci run --wasm github release_upload $TAG $FILE
          done
        env:
          RELEASE_VERSION: v${{ inputs.tag || github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: webui/rockbox/release/${{ env.RELEASE_VERSION }}
